name: Monthly Invoice
on: 
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip

      - name: Execute Python Script
        run: python script.py

        
      # - name: Update CSV
      #   uses: actions/update_csv@v1

      # - name: Generate Invoices
      #   uses: actions/generate_invoices@v1

        

      # - name: Send Invoices
      #   uses: actions/send_invoices@v1
